### PR TITLE
Update flow-bin peer dependency

### PR DESCRIPTION
**Pull request by sanghin**

### CODE REVIEW

**Comment by amilajack** [comment]
Thanks

**Comment by CodyReichert** [comment]
Was this released yet? Looks like `3.3.5` is still the latest on NPM.

Thanks for the update - let me know if I can help get it released!

**Comment by amilajack** [comment]
This was just pushed in `3.3.6`. Thanks for reminding me about this

**Comment by CodyReichert** [comment]
Great news, thank you!

**Pull request merged**
