### PR TITLE
Move `flow-bin` into peerDependencies

### PR DESCRIPTION
**Pull request by zperrault**
Also adds `flow-bin` to `devDependencies` so tests can use it

Addresses #7

@amilajack Is there a particular version of `flow-bin` that we need to require?

### CODE REVIEW

**Comment by amilajack** [comment]
Tests are failing because of something i did. Ignore the failing appveyor test. I'll publish this into a prerelease after doing a couple of fixes.

**Comment by amilajack** [comment]
Also just published `1.5.0`. If an error blames another file, the blame filename and line number is show.

**Comment by amilajack** [comment]
Did you test this locally?

**Comment by jfmengels** [comment]
Since you now can't be sure that `flow-bin` is available, there should be an error if it can't be found.

**Comment by zperrault** [comment]
@amilajack I ran tests locally. I'm making a small test project now to link the module into and make sure it all still works okay.

**Comment by zperrault** [comment]
@jfmengels Do you mean we should output a different error than the ones that npm and the `require` will output?

`npm` will throw if a peerDep isn't met and if someone somehow gets past that, the call to `require('flow-bin')` will throw a module not found error.

**Comment by zperrault** [comment]
I linked the module locally, ran an `npm prune --production` in the module directory, linked it into a small project with `flow-bin` as a devDep and everything is working as expected.

I _think_ that's as close to really testing this kind of change as I can get without their being a prerelease I can install and have npm do everything it does normally.

**Comment by jfmengels** [comment]
> @jfmengels Do you mean we should output a different error than the ones that npm and the require will output?

Yes.

> npm will throw if a peerDep isn't met and if someone somehow gets past that, the call to require('flow-bin') will throw a module not found error.

Agreed, but I think it would be nice to have a nice error. Otherwise, people will think that it's a bug from this plugin and they may start creating issues about it.

**Comment by amilajack** [comment]
> Agreed, but I think it would be nice to have a nice error. Otherwise, people will think that it's a bug from this plugin and they may start creating issues about it.

I can second this. ESlint handles this very nicely.

**Comment by zperrault** [comment]
Happy to add some nice errors to this tomorrow morning. (I'm on central time)

Thank you for looking at this so quickly.

**Comment by zperrault** [comment]
@amilajack Do you have an example of this? ` ESlint handles this very nicely.`

**Comment by amilajack** [comment]
Sure!
```
popcorn-time-desktop|update-deps⚡ ⇒ npm run lint

> popcorn-time-desktop@0.0.6 lint /Users/amila/Documents/Projects/popcorn-time-desktop
> eslint --cache --ignore-path .gitignore --format=node_modules/eslint-formatter-pretty app test *.js && stylelint app/styles/*.scss app/styles/**/*.scss


Oops! Something went wrong! :(

ESLint couldn't find the plugin "eslint-plugin-react". This can happen for a couple different reasons:

1. If ESLint is installed globally, then make sure eslint-plugin-react is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.

2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm i eslint-plugin-react@latest --save-dev

If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.


npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/7.0.0/bin/node" "/usr/local/bin/npm" "run" "lint"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! popcorn-time-desktop@0.0.6 lint: `eslint --cache --ignore-path .gitignore --format=node_modules/eslint-formatter-pretty app test *.js && stylelint app/styles/*.scss app/styles/**/*.scss`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the popcorn-time-desktop@0.0.6 lint script 'eslint --cache --ignore-path .gitignore --format=node_modules/eslint-formatter-pretty app test *.js && stylelint app/styles/*.scss app/styles/**/*.scss'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the popcorn-time-desktop package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint --cache --ignore-path .gitignore --format=node_modules/eslint-formatter-pretty app test *.js && stylelint app/styles/*.scss app/styles/**/*.scss
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs popcorn-time-desktop
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls popcorn-time-desktop
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/amila/Documents/Projects/popcorn-time-desktop/npm-debug.log
popcorn-time-desktop|update-deps⚡ ⇒
```

**Comment by zperrault** [comment]
Just updated with an error message modeled after the eslint ones. Happy to change the copy in any way y'all'd like 😄 

```

Oops! Something went wrong! :(

eslint-plugin-flowtype-errors could not find the package "flow-bin". This can happen for a couple different reasons.

1. If ESLint is installed globally, then make sure "flow-bin" is also installed globally.

2. If ESLint is installed locally, then it's likely that "flow-bin" is not installed correctly. Try reinstalling by running the following:

  npm i -D flow-bin@latest

```

**Comment by zperrault** [comment]
@amilajack @jfmengels Anything else we need on this to get it read to merge into `master`? I'm assuming this is a major version bump?

**Comment by amilajack** [comment]
I'll merge this and release it as a premajor! Would be great if you guys could test it.

**Comment by amilajack** [comment]
Released as `eslint-plugin-flowtype-errors@2.0.0-0` 😊

**Comment by amilajack** [comment]
Totally forgot that we should add something about installing `flow-bin` in the readme

**Pull request merged**
