### PR TITLE
Update to support Flow >= 0.66

### LINKED ISSUE #115: Support latest version of Flow (0.66)
Flow error messages got an overhaul in [Flow 0.66](https://github.com/facebook/flow/releases/tag/v0.66.0). Using this latest release with `eslint-plugin-flowtype-errors` produces linting errors that just look like this:

screen shot 2018-02-20 at 9 39 27 am

### PR DESCRIPTION
**Pull request by nwoltman**
Fixes #115

### CODE REVIEW

**Comment by jdmota** [comment]
Looks good. Thanks for your help!

Is this a breaking change? Will it work with previous versions of flow?

**Comment by nwoltman** [comment]
It will still work with previous versions of Flow, it just won't produce great error messages. It depends on whether or not you consider the change to `peerDependencies` to be breaking.

**Comment by jdmota** [comment]
What do you think about using `--json-version=2`?

Just found out about it. It seems very useful. https://github.com/facebook/flow/commit/28c8a3e5acd7ca9f17547ca38e54efd8475f9eb3

Especially `primaryLoc` and `messageMarkup`.

**Comment by nwoltman** [comment]
The end result will be the exact same, although the code for it will be less hacky (like [this regex replace](https://github.com/amilajack/eslint-plugin-flowtype-errors/pull/118/files#diff-d2e0be6ec291992ef30c98ccd07ffc6dR116)). I can look into using it.

**Comment by nwoltman** [comment]
@amilajack Updated. Should `package-lock.json` be added to the `.gitignore`?

**Comment by amilajack** [comment]
Good idea. it should be

**Comment by nwoltman** [comment]
I added a separate commit for ignoring the `package-lock.json`

**Comment by jdmota** [comment]
Looks good. But I think it should only be merged after #116, and that we should leave a note saying that with previous versions of flow, it might not produce great error messages (or just release as 4.0.0, but in that case, we might as well use `--json-version=2`, to make the code simpler).

**Comment by amilajack** [comment]
We can merge after merge conflicts are fixed

**Comment by nwoltman** [comment]
Fixed conflicts

**Comment by amilajack** [comment]
Published this in `eslint-plugin-flowtype-errors@next` 🎉 Please test this out and let me know if it works for you

**Comment by nwoltman** [comment]
It's working fine for me 👍

**Comment by lydell** [comment]
Thank you so much for doing this! :tada:

**Pull request merged**
