### PR TITLE
Add "uncovered" rule, to individually lint against uncovered expressions

### PR DESCRIPTION
**Pull request by jaredly**
On my team we find this method much more valuable than "coverage percentages", but we've been using our own custom linter for it -- we'd much rather have it integrated with eslint, so I figured I'd see if you're interested in having it added here :D 

Here's what it looks like in action:
image

### CODE REVIEW

**Review by amilajack — CHANGES_REQUESTED** [review]
Love the addition! I think it would be good to add some unit tests for this before merging.

**Comment by jaredly** [comment]
oh good call :)

**Review by amilajack — APPROVED** [review]

**Comment by amilajack** [comment]
🥳 nice!

**Comment by jaredly** [comment]
woohoo!!! just so I know what to expect -- do you have an idea of when you'll release a new version?

**Comment by amilajack** [comment]
asap. working on bumping dependencies now and i'll bump after that

**Comment by amilajack** [comment]
@jaredly Published this in https://github.com/amilajack/eslint-plugin-flowtype-errors/releases/tag/v4.4.0-0. Try the prerelease out with `npm install eslint-plugin-flowtype-errors@next` and let me know if this works for you. If it does, I'll publish `4.4.0`

**Comment by jaredly** [comment]
yup looks perfect! Thank you so much for the quick response!

**Comment by amilajack** [comment]
Published `4.4.0` 🥳

**Pull request merged**
