### PR TITLE
Fix #95

### LINKED ISSUE #95: 'error Unexpected token' then combined with 'vue-eslint-parser'
Please look at this comment:
https://github.com/mysticatea/vue-eslint-parser/issues/10#issuecomment-317260155

### PR DESCRIPTION
**Pull request by jdmota**
- [X] Add a test that uses `eslint-plugin-vue`
- [ ] ~~Fix "Required module not found" for Vue?~~

### CODE REVIEW

**Comment by amilajack** [comment]
@jdmota is this ready to be merged?

**Comment by jdmota** [comment]
I think it is, because I don't see a way to tell flow that the required module exists.

I think it's better to have some kind of support for html rather than none.

**Comment by jdmota** [comment]
Let me resolve conflicts first.

**Comment by jdmota** [comment]
@amilajack Do you think this is ready for merging?

**Comment by amilajack** [comment]
Thanks for this PR and sorry for the delay. Pushed this in `3.3.7`

**Pull request merged**
