### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by jdmota**
I've made some refactoring (to reduce repetition of code) and ensured that when running `yarn run check` (or `flow`), we don't check the test files.

- [x] Should we run flow on CI? Since we now have type checking?

### CODE REVIEW

**Comment by amilajack** [comment]
Should we run flow on CI? Sure! I remember the project having a bunch of flow issues tho. Let's try to find a way to install `flow-typed` definitions after cloning the project. Using the postinstall npm hook wont work.

**Comment by jdmota** [comment]
Not sure how `flow-typed` will be useful to us. The only dependencies are `babel-runtime` (which we never run directly) and `slash`, and I think there is no type definition for `slash`.

Unless you want to type check `test/format.spec.js` too, in that case, I have to make some changes.

**Comment by jdmota** [comment]
By the way, why do we have `react` as a devDependency? 😜

**Comment by jdmota** [comment]
> It seems like the yarn.lock file was removed from version control.

I removed `react` from dev dependencies, that is why there are many removed lines. But the file seems to be there.

Are you sure?

**Comment by amilajack** [comment]
Ahhh woops my bad. Thanks for this!

**Pull request merged**
