### PR TITLE
introduce enforce-min-coverage rule

### PR DESCRIPTION
**Pull request by jzimmek**
The enforce-min-coverage rule takes the required coverage (as percentage) as an option:

```
...
  rules:
    strict: 0
    flowtype-errors/show-errors: 2
    flowtype-errors/enforce-min-coverage:
      - 2
      - 50
...
```

Closes https://github.com/amilajack/eslint-plugin-flowtype-errors/issues/65

### CODE REVIEW

**Comment by amilajack** [comment]
Would be nice if you could add some tests to this PR. You should probably add both e2e tests by adding to the the `./test/codebases` tests and the `./test/*.example.js` tests

**Comment by amilajack** [comment]
Thanks for the PR! Will push a beta release for this

**Comment by amilajack** [comment]
Just pushed `3.2.2-0`. Also would be great if you could document the new eslint rule

**Comment by jzimmek** [comment]
Cool! Will add some docs soon.

**Pull request merged**
